config/routes.rb
Rails.application.routes.draw do
  get '/game', to: 'gaming#game'

  get '/score', to: 'gaming#score'

  get '/', to: 'gaming#game'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/gaming_controller.rb
require 'open-uri'
require 'json'

class GamingController < ApplicationController
  def game
    @grid = generate_grid
    @start_time = Time.now
  end

  def score
    finish_time = Time.now
    @my_word = params[:my_word]
    @grid = params[:grid].split(//)
    start_time = params[:start_time].to_time
    @result = run_game(@my_word, @grid, start_time, finish_time)
    session[:number_of_session] ||= 0
    session[:number_of_session] +=1
    session[:total_score] ||= 0
    session[:total_score] += @result[:score]
    session[:avg_score] ||= 0
    session[:avg_score] = session[:total_score] / session[:number_of_session]
  end

private

  def generate_grid
    # TODO: generate random grid of letters
    grid = []
    (0..7).each do |i|
      grid[i] = ("A".."Z").to_a.sample(1)
    end
    return grid
  end

  def run_game(attempt, grid, start_time, end_time)
  # TODO: runs the game and return detailed hash of result
  attempt_formatted = attempt.upcase.split(//)
  grid_mod = Hash.new(0)
  attempt_hash = Hash.new(0)
  result = {
    time: (end_time - start_time).round(3)
  }
  if result[:time] > 30
    result[:score] = 0
    result[:translation] = nil
    result[:message] = "too slow..."
    return result
  end

  grid.each do |letter|
    if attempt_formatted.include?(letter)
      grid_mod[letter] += 1
    end
  end

  attempt_formatted.each do |letter|
    attempt_hash[letter] += 1
  end

  if grid_mod.keys.sort == attempt_hash.keys.sort
    grid_mod.each do |key, _value|
      if grid_mod[key] < attempt_hash[key]
        result[:score] = 0
        result[:translation] = nil
        result[:message] = "not in the grid"
      end
    end
  else
    result[:score] = 0
    result[:translation] = nil
    result[:message] = "not in the grid"
  end

  unless result[:score] == 0
    api_url = "http://api.wordreference.com/0.8/80143/json/enfr/#{attempt}"

    open(api_url) do |f|
      api_res = JSON.parse(f.read)
      if api_res.keys[0] == "Error"
        result[:score] = 0
        result[:translation] = nil
        result[:message] = "not an english word"
      else
        result[:score] = (attempt.size * 30 - result[:time]).round
        result[:translation] = api_res["term0"]["PrincipalTranslations"]["0"]["FirstTranslation"]["term"]
        result[:message] = "well done"
      end
    end
  end
  return result
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gaming_helper.rb
module GamingHelper
end

app/views/gaming/game.html.erb
<h1>Welcome to the longuest word</h1>

<h3>Here is your grid :</h3>
<table>
  <tr>
    <% @grid.each do |letter| %>
      <td><%= letter[0]  %></td>
    <% end %>
  </tr>
</table>
<form action="/score">
  <label for="">What's your best shot?</label>
  <input type="text" name="my_word">
  <input type="hidden" name="start_time" value="<%= @start_time %>" >
  <input type="hidden" name="grid" value="<%= @grid.join(' ') %>">
  <input type="submit" value="Submit!">
</form>

app/views/gaming/score.html.erb
<h1>Results</h1>
<h3>Mean score : <%=session[:avg_score] %> on <%= session[:number_of_sessions] %> games</h3>
<h3>Here was your grid :</h3>
<table>
  <tr>
    <% @grid.each do |letter| %>
      <td><%= letter[0]  %></td>
    <% end %>
  </tr>
</table>
<h3>Your best shot : <%= @my_word %></h3>
<h3>Score : <%= @result[:score] %></h3>
<h3><%= @result[:message] %></h3>
<h3>Elapsed time (s): <%= @result[:time] %></h3>
<h3>French translation : <em><%= @result[:translation] %></em></h3>
<%= link_to "Try again", game_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LonguestWord</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>